---
- hosts: webservers
  tasks:
    - name: install pip3
      apt:
        update_cache: yes
        name: python3-pip
      become: yes

    - name: Install Docker
      apt:
        name: docker.io
      become: yes

    - name: Start Docker
      shell: |
        systemctl start docker
        systemctl enable docker
      become: yes

    - name: Pull Frontend app locally
      shell: |
        docker pull papeterinnova/vaana-front:v1.3.3-stable
      become: yes

    - name: Run Image
      shell: |
        docker run -d -p 8083:80 --name vaana_front papeterinnova/vaana-front:v1.3.3-stable
      become: yes
