---
- hosts: webservers
  tasks:
    - name: install pip3
      apt:
        update_cache: yes
        name: python3-pip
      become: yes

    - name: Install Docker
      apt:
        name: docker.io
      become: yes

    - name: Start Docker
      shell: |
        systemctl start docker
        systemctl enable docker
      become: yes

    - name: Pull Frontend app locally
      shell: |
        docker pull papeterinnova/vaana-new-ui:v0.1
      become: yes

    # - name: Kill Previous container
    #   shell: |
    #     docker kill new_ui
    #   become: yes

    # - name: Prune container
    #   yes: 'y' |
    #     docker container prune
    #   become: yes

    # - name: Prune everything
    #   docker_prune:
    #     containers: yes
    #     volumes: yes

    - name: Run Image
      shell: |
        docker run -d -p 8084:80 --name new_ui papeterinnova/vaana-new-ui:v0.1
      become: yes
